### ISSUE TITLE
master branch builds are broken

### ISSUE THREAD

**Issue by JPWKU** [edgexfoundry/security-api-gateway#19]
The master branch builds on security-api-gateway are currently broken.  This will require some refactoring because of the dependency on edgex-go, which has undergone some refactoring/restructuring.  I would suggest liaising with the edgex-go team to learn about the restructure going on there.

**Comment by tingyuz** [comment]
this is due to the change of the package path in edgex-go, i will get it fixed and have a PR for it.

**Comment by tingyuz** [comment]
fixed in PR #20.

**Comment by tingyuz** [comment]
close the issue as the fix has been merged.
