### ISSUE TITLE
upload cert to kong fail

### ISSUE THREAD

**Issue by lesliechung88** [edgexfoundry/security-api-gateway#21]
edgex-proxy log info:

| INFO: 2018/09/01 02:44:11 successful on retrieving certificate from v1/secret/edgex/pki/tls/edgex-kong.
edgex-proxy        | INFO: 2018/09/01 02:44:11 Trying to upload cert to proxy server.
edgex-proxy        | **ERROR: 2018/09/01 02:44:11 Failed to add certificate with errorcode 400.**
edgex-proxy        | INFO: 2018/09/01 02:44:11 Finishing initialization for reverse proxy.
--------------------------------------------------------------------
kong log info:
kong               | 172.29.0.9 - - [01/Sep/2018:02:44:11 +0000] "POST /certificates/ HTTP/1.1" 400 37 "-" "Go-http-client/1.1"

**Comment by tingyuz** [comment]
This could be due to two possible reasons. 
1. The cert retrieved from the secret store is invalid.
2. the path/request to upload the cert is incorrect. 

The Delhi release has improvement on both cases. Please update to the latest release and check if the issue still happens.
