### ISSUE TITLE
The Host Header should be configurable when generating OAuth tokens

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/security-api-gateway#40]
Currently, the `Host` header is always set to `edgex`, which will fail if the user is attempting to create the OAuth token over HTTPS and uses a SNI/hostname setting other than `edgex`, as the certificate validation will fail. This setting should be configurable.

**Comment by tingyuz** [comment]
will switch from hardcode to snis section of [secretservice] section in the configuration file. This will be addressed in Delhi dot release.

**Comment by tingyuz** [comment]
address in PR #47

**Comment by tingyuz** [comment]
I will propose to remove host header as it is not gaining any benefit. Besides based on my testing on KONG 1.0.3 it seems there is a bug with combination of custom header and JWT/OAuth2 auth plugin.

**Comment by tingyuz** [comment]
close this issue per my comments above.
