### ISSUE TITLE
Messages reference JWT when OAuth2 tokens are being used

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/security-api-gateway#42]
This may be a misunderstanding on my part, but when choosing to use OAuth2 tokens, JWT shouldn't be used at all, but the messages here:

https://github.com/edgexfoundry/security-api-gateway/blob/a1603d1c9a577cf3e8018701906c3cb1a7d5a40d/core/accounts.go#L181

and here:

https://github.com/edgexfoundry/security-api-gateway/blob/a1603d1c9a577cf3e8018701906c3cb1a7d5a40d/core/accounts.go#L185

still reference JWT.

**Comment by tingyuz** [comment]
The log should change from JWT to bearer token. This will be addressed in the Delhi dot release.

**Comment by tingyuz** [comment]
addressed in PR #47.
