### ISSUE TITLE
Upgrade Kong (Edinburgh Roadmap Item)

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/security-api-gateway#45]
Upgrade to 0.14.1 for Kong

**Comment by anonymouse64** [comment]
I thought we were already using 0.13.0 for Delhi? 

We could however upgrade to 0.14.0 for Edinburgh

**Comment by jpwhitemn** [comment]
correct @anonymouse64 - upgrade to 0.14.1.  My mistake and I have updated.

**Comment by tingyuz** [comment]
The latest release of KONG is 1.0.3 which introduces a couple of broken changes of the APIs including ACL/OAuth2. I am working actively to upgrade our codebase for the new version.

**Comment by tingyuz** [comment]
This issue is fixed with #55 .
