### ISSUE TITLE
docker-compose.yml should be a symlink not a text file.

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/security-api-gateway#48]
https://github.com/edgexfoundry/security-api-gateway/blob/a5840be551caacb95405538cc2871328a4d5b661/docker-compose.yml#L1

Believe this file was intended to be a symlink and not a text file.

P.S. using this ticket to measure process throughput time; please do not jump in and fix immediately.

**Comment by tingyuz** [comment]
Fixed and closed.
