### ISSUE TITLE
Convert to Go Module

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/security-api-gateway#52]
This service needs to be converted to a Go module in order to eliminate the use of glide.

More information
https://github.com/golang/go/wiki/Modules#migrating-to-modules

If there is a current dependency on edgex-go in this service, that should be refactored to instead use https://github.com/edgexfoundry/go-mod-core-contracts

**Comment by lenny-intel** [comment]
Jim Wang (jim-wang-intel) with take this.

**Comment by tingyuz** [comment]
I just tried make build and have the error below. Do we need to adjust the logging package?

cd core && CGO_ENABLED=0 GO111MODULE=on GOOS=linux GOARCH=amd64 go build  -o  edgexproxy .
main.go:27:2: cannot find package "github.com/edgexfoundry/go-mod-core-contracts/clients/logging" in any of:
        C:\Go\src\github.com\edgexfoundry\go-mod-core-contracts\clients\logging (from $GOROOT)
        C:\CodeSamples\go\src\github.com\edgexfoundry\go-mod-core-contracts\clients\logging (from $GOPATH)
make: *** [Makefile:19: build] Error 1

**Comment by jim-wang-intel** [comment]
@tsconn23 & @jpwhitemn  the security-api-gateway is now in go-module, this issue should be in verified state and can be closed.

**Comment by tingyuz** [comment]
Close the issue.
