### ISSUE TITLE
Remove make prepare target

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/security-api-gateway#58]
As per the upgrade to go modules and https://github.com/edgexfoundry/edgex-go/issues/1275 we should confirm that the make prepare step isn't used by the jenkins jobs for this repo and remove the prepare target from the Makefile

**Comment by tingyuz** [comment]
Fixed.

**Comment by anonymouse64** [comment]
@tingyuz what PR was this fixed with?

**Comment by tingyuz** [comment]
It is within #66. Reopen to track the status.

**Comment by tingyuz** [comment]
since #66 is merged, close this issue.
