### ISSUE TITLE
cannot load certs from vault

### ISSUE THREAD

**Issue by lesliechung88** [edgexfoundry/security-api-gateway#65]
edinburgh release
cannot load certs from vault , because no right

tokenpath = "/vault/config/assets/resp-init.json"

 should be :
 tokenpath = "/vault/config/assets/admin-token.json"

[secretservice]
server = "edgex-vault"
port = "8200"
healthcheckpath = "v1/sys/health"
certpath = "v1/secret/edgex/pki/tls/edgex-kong"
tokenpath = **"/vault/config/assets/resp-init.json"**
cacertpath = "/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem"

**Comment by lesliechung88** [comment]
should be :
tokenpath = "/vault/config/assets/kong-token.json"

**Comment by tingyuz** [comment]
This is intentional - the reason is that the current implementation of secret service has issue with renewal of kong-token when it is expired, so we are using master token instead. Once the issue is fixed in the secret service we can switch back to kong-token.
