### ISSUE TITLE
Delete docker-compose.yml symlink

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/security-api-gateway#67]
There is an issue with forking this repo because of a symlink to the docker-compose.yml file that has been checked into git.

See here:
https://github.com/edgexfoundry/security-api-gateway/blob/master/docker-compose.yml

This then always shows up as a modification in git when I do a fresh fork and clone, presumably because the path doesn't exist in my local filesystem.

```
lrwxr-xr-x   1 tconn  staff     13 Jun 13 20:20 docker-compose.yml -> !<symlink>??d
```

Request that the symlink be removed from this repo as it isn't much use to a local dev.

**Comment by tingyuz** [comment]
removed from the project.

**Comment by tsconn23** [comment]
@tingyuz I'm not sure where this got resolved. The link I provided in the initial issue report is still valid and I don't see an associated PR that was merged. I just re-forked from this repo and the symlink is still present.

**Comment by tingyuz** [comment]
I reuse the same file name with content but not linked to the other docker-composer file in the previous fix. Make another push by deleting the file completely to see if it fixes your issue. can you try it again?
