### ISSUE TITLE
Service is not runnable on non-Linux OS

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/security-api-gateway#69]
The `GO` environment variable used to build the service is defined in the `Makefile` to compile explicitly for Linux.

`GO=CGO_ENABLED=0 GO111MODULE=on GOOS=linux go`

After building the service, trying to run it on a non-Linux machine, like a Mac, produces the following error:
```
~/Documents/code/git/tsconn23/security-api-gateway $ make run
cd cmd/edgexproxy && ./edgexproxy init=true
/bin/sh: ./edgexproxy: cannot execute binary file
make: *** [run] Error 126
```
This makes the service impossible to test locally without Makefile changes unless one is running Linux.

**Comment by tingyuz** [comment]
removed target OS in the Makefile in the #66.
